include: package:flutter_lints/flutter.yaml
code-style: 
  format: true
linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_use_package_imports: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_empty_else: true
    curly_braces_in_flow_control_structures: true