name: im_okay
description: A check-in app for times of peril.
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  provider: ^6.0.5
  go_router: ^12.0.1
  intl: any
  http: ^1.1.0
  firebase_messaging: ^14.7.2
  equatable: ^2.0.5
  getwidget: ^4.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
