name: im_okay
description: A check-in app for times of peril.
publish_to: 'none'
version: 1.0.2+7

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  provider: ^6.0.5
  go_router: ^14.3.0
  intl: any
  http: ^1.1.0
  firebase_messaging: ^15.1.5
  equatable: ^2.0.5
  getwidget: ^4.0.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.2
  json: ^0.20.2
  logger: ^2.4.0
  geolocator: ^13.0.2
  point_in_polygon: ^1.0.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
